# Generated by Django 4.2 on 2026-02-20 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DapilKabKota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(db_index=True, max_length=200, verbose_name='Nama Dapil Kab/Kota')),
                ('kursi', models.IntegerField(default=0, verbose_name='Alokasi Kursi')),
            ],
            options={
                'verbose_name': 'Dapil Kab/Kota',
                'verbose_name_plural': 'Data Dapil Kab/Kota',
            },
        ),
        migrations.CreateModel(
            name='DapilProvinsi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(db_index=True, max_length=200, verbose_name='Nama Dapil Provinsi')),
                ('kursi', models.IntegerField(default=0, verbose_name='Alokasi Kursi')),
            ],
            options={
                'verbose_name': 'Dapil Provinsi',
                'verbose_name_plural': 'Data Dapil Provinsi',
            },
        ),
        migrations.CreateModel(
            name='DapilRI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(db_index=True, max_length=200, verbose_name='Nama Dapil RI')),
                ('kursi', models.IntegerField(default=0, verbose_name='Alokasi Kursi')),
            ],
            options={
                'verbose_name': 'Dapil RI',
                'verbose_name_plural': 'Data Dapil RI',
            },
        ),
        migrations.CreateModel(
            name='KabupatenKota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(db_index=True, max_length=200, verbose_name='Nama Kabupaten/Kota')),
                ('dapil_provinsi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kabupaten_set', to='core.dapilprovinsi', verbose_name='Dapil Provinsi')),
                ('dapil_ri', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kabupaten_set', to='core.dapilri', verbose_name='Dapil RI')),
            ],
            options={
                'verbose_name': 'Kabupaten/Kota',
                'verbose_name_plural': 'Data Kabupaten/Kota',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Kecamatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(db_index=True, max_length=200, verbose_name='Nama Kecamatan')),
                ('dapil_kab_kota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kecamatan_set', to='core.dapilkabkota', verbose_name='Dapil Kab/Kota')),
                ('kabupaten_kota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kecamatan_set', to='core.kabupatenkota', verbose_name='Kabupaten/Kota')),
            ],
            options={
                'verbose_name': 'Kecamatan',
                'verbose_name_plural': 'Data Kecamatan',
                'ordering': ['nama'],
                'unique_together': {('kabupaten_kota', 'nama')},
            },
        ),
        migrations.CreateModel(
            name='Partai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_urut', models.IntegerField(db_index=True, unique=True, verbose_name='No. Urut')),
                ('nama', models.CharField(db_index=True, max_length=200, verbose_name='Nama Partai')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partai_logos/', verbose_name='Logo Partai')),
                ('warna_hex', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Warna Identitas (HEX)')),
            ],
            options={
                'verbose_name': 'Partai',
                'verbose_name_plural': 'Data Partai',
                'ordering': ['no_urut'],
            },
        ),
        migrations.CreateModel(
            name='TPSDPTPilkada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_tps', models.IntegerField(default=0, verbose_name='Total TPS Pilkada')),
                ('jumlah_dpt', models.IntegerField(default=0, verbose_name='DPT Pilkada Serentak')),
                ('kecamatan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tpsdpt_pilkada', to='core.kecamatan', verbose_name='Kecamatan')),
            ],
            options={
                'verbose_name': 'TPSDPT Pilkada',
                'verbose_name_plural': 'Data TPSDPT Pilkada',
            },
        ),
        migrations.CreateModel(
            name='TPSDPTPemilu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_tps', models.IntegerField(default=0, verbose_name='Total TPS Pemilu')),
                ('jumlah_dpt', models.IntegerField(default=0, verbose_name='DPT Pemilu Serentak')),
                ('kecamatan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tpsdpt_pemilu', to='core.kecamatan', verbose_name='Kecamatan')),
            ],
            options={
                'verbose_name': 'TPSDPT Pemilu',
                'verbose_name_plural': 'Data TPSDPT Pemilu',
            },
        ),
        migrations.AddField(
            model_name='dapilkabkota',
            name='kabupaten_kota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dapil_kab_set', to='core.kabupatenkota', verbose_name='Kabupaten/Kota'),
        ),
        migrations.CreateModel(
            name='KelurahanDesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(db_index=True, max_length=200, verbose_name='Nama Kelurahan/Desa')),
                ('dapil_kab_kota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desa_set', to='core.dapilkabkota', verbose_name='Dapil Kab/Kota')),
                ('kecamatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desa_set', to='core.kecamatan', verbose_name='Kecamatan')),
            ],
            options={
                'verbose_name': 'Kelurahan/Desa',
                'verbose_name_plural': 'Data Kelurahan/Desa',
                'ordering': ['nama'],
                'unique_together': {('kecamatan', 'nama')},
            },
        ),
    ]
