# Generated by Django 4.2 on 2026-02-21 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tpsdptpemilu',
            options={'verbose_name': 'Data TPS & DPT Pemilu', 'verbose_name_plural': 'Data TPS & DPT Pemilu'},
        ),
        migrations.AlterModelOptions(
            name='tpsdptpilkada',
            options={'verbose_name': 'Data TPS & DPT Pilkada', 'verbose_name_plural': 'Data TPS & DPT Pilkada'},
        ),
    ]
