# Generated by Django 4.2 on 2026-02-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_urut', models.IntegerField(unique=True, verbose_name='Nomor Urut')),
                ('nama_partai', models.CharField(max_length=200, verbose_name='Nama Partai')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partai_logos/', verbose_name='Logo Partai')),
            ],
            options={
                'verbose_name': 'Partai',
                'verbose_name_plural': 'Partai',
                'ordering': ['no_urut'],
            },
        ),
    ]
