# Generated by Django 4.2 on 2026-02-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemilu2024', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partai',
            options={'ordering': ['no_urut'], 'verbose_name': 'Data Partai', 'verbose_name_plural': 'Data Partai'},
        ),
        migrations.CreateModel(
            name='PaslonPilpres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_urut', models.IntegerField(unique=True, verbose_name='Nomor Urut')),
                ('nama_capres', models.CharField(max_length=200, verbose_name='Nama Calon Presiden')),
                ('nama_cawapres', models.CharField(max_length=200, verbose_name='Nama Calon Wakil Presiden')),
                ('foto_paslon', models.ImageField(blank=True, null=True, upload_to='paslon_photos/', verbose_name='Foto Paslon')),
                ('koalisi', models.ManyToManyField(blank=True, to='pemilu2024.partai', verbose_name='Partai Koalisi')),
            ],
            options={
                'verbose_name': 'Paslon Pilpres',
                'verbose_name_plural': 'Data Paslon Pilpres',
                'ordering': ['no_urut'],
            },
        ),
    ]
