# Generated by Django 4.2 on 2026-02-16 16:51

from django.db import migrations, models
import django.db.models.deletion
import pemilu2024.models


class Migration(migrations.Migration):

    dependencies = [
        ('pemilu2024', '0002_alter_partai_options_paslonpilpres'),
    ]

    operations = [
        migrations.CreateModel(
            name='KabupatenKota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Daerah')),
                ('jenis', models.CharField(choices=[('PROV', 'Provinsi'), ('KAB', 'Kabupaten'), ('KOTA', 'Kota')], max_length=5, verbose_name='Jenis')),
            ],
            options={
                'verbose_name': 'Kabupaten/Kota',
                'verbose_name_plural': 'Data Kabupaten/Kota',
                'ordering': ['jenis', 'nama'],
                'unique_together': {('nama', 'jenis')},
            },
        ),
        migrations.AlterField(
            model_name='partai',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=pemilu2024.models.partai_logo_path, verbose_name='Logo Partai'),
        ),
        migrations.AlterField(
            model_name='paslonpilpres',
            name='foto_paslon',
            field=models.ImageField(blank=True, null=True, upload_to=pemilu2024.models.paslon_photo_path, verbose_name='Foto Paslon'),
        ),
        migrations.AlterField(
            model_name='paslonpilpres',
            name='koalisi',
            field=models.ManyToManyField(blank=True, to='pemilu2024.partai', verbose_name='Gabungan Partai Politik Pengusul'),
        ),
        migrations.CreateModel(
            name='PaslonPilkada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_urut', models.IntegerField(verbose_name='Nomor Urut')),
                ('nama_cakada', models.CharField(max_length=200, verbose_name='Nama Calon Kepala Daerah')),
                ('nama_cawakada', models.CharField(max_length=200, verbose_name='Nama Calon Wakil Kepala Daerah')),
                ('foto_paslon', models.ImageField(blank=True, null=True, upload_to=pemilu2024.models.pilkada_photo_path, verbose_name='Foto Paslon')),
                ('kabupaten_kota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paslon_set', to='pemilu2024.kabupatenkota', verbose_name='Kabupaten/Kota')),
                ('koalisi', models.ManyToManyField(blank=True, related_name='paslon_pilkada_set', to='pemilu2024.partai', verbose_name='Gabungan Partai Politik Pengusul')),
            ],
            options={
                'verbose_name': 'Paslon Pilkada',
                'verbose_name_plural': 'Data Paslon Pilkada',
                'ordering': ['kabupaten_kota', 'no_urut'],
                'unique_together': {('kabupaten_kota', 'no_urut')},
            },
        ),
    ]
