# Generated by Django 4.2 on 2026-02-16 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pemilu2024', '0003_kabupatenkota_alter_partai_logo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kabupatenkota',
            options={'ordering': ['nama'], 'verbose_name': 'Kabupaten/Kota', 'verbose_name_plural': 'Data Kabupaten/Kota'},
        ),
        migrations.AlterUniqueTogether(
            name='kabupatenkota',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='kabupatenkota',
            name='nama',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nama Daerah'),
        ),
        migrations.AlterField(
            model_name='paslonpilkada',
            name='kabupaten_kota',
            field=models.ForeignKey(blank=True, help_text='Kosongkan jika Paslon tingkat Provinsi (Jawa Barat)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paslon_set', to='pemilu2024.kabupatenkota', verbose_name='Kabupaten/Kota'),
        ),
        migrations.RemoveField(
            model_name='kabupatenkota',
            name='jenis',
        ),
    ]
