# Generated by Django 4.2 on 2026-02-16 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pemilu2024', '0004_alter_kabupatenkota_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paslonpilkada',
            options={'ordering': ['jenis_pilkada', 'kabupaten_kota', 'no_urut'], 'verbose_name': 'Paslon Pilkada', 'verbose_name_plural': 'Data Paslon Pilkada'},
        ),
        migrations.AlterUniqueTogether(
            name='paslonpilkada',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='paslonpilkada',
            name='jenis_pilkada',
            field=models.CharField(choices=[('PROV', 'Provinsi (Pilgub)'), ('KOKAB', 'Kabupaten/Kota (Pilbup/Pilwalkot)')], default='KOKAB', max_length=10, verbose_name='Jenis Pilkada'),
        ),
        migrations.AlterField(
            model_name='paslonpilkada',
            name='kabupaten_kota',
            field=models.ForeignKey(blank=True, help_text='Pilih daerah jika Jenis Pilkada adalah Kabupaten/Kota. Kosongkan untuk tingkat Provinsi.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paslon_set', to='pemilu2024.kabupatenkota', verbose_name='Kabupaten/Kota'),
        ),
        migrations.AlterUniqueTogether(
            name='paslonpilkada',
            unique_together={('jenis_pilkada', 'kabupaten_kota', 'no_urut')},
        ),
    ]
