# Generated by Django 4.2 on 2026-02-16 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pemilu2024', '0005_alter_paslonpilkada_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kecamatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Kecamatan')),
                ('kabupaten_kota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kecamatan_set', to='pemilu2024.kabupatenkota', verbose_name='Kabupaten/Kota')),
            ],
            options={
                'verbose_name': 'Kecamatan',
                'verbose_name_plural': 'Data Kecamatan',
                'ordering': ['kabupaten_kota', 'nama'],
                'unique_together': {('kabupaten_kota', 'nama')},
            },
        ),
    ]
