# Generated by Django 4.2 on 2026-02-16 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pemilu2024', '0006_kecamatan'),
    ]

    operations = [
        migrations.CreateModel(
            name='KelurahanDesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desa_kelurahan', models.CharField(max_length=150, verbose_name='Desa/Kelurahan')),
                ('kabupaten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pemilu2024.kabupatenkota', verbose_name='Kabupaten/Kota')),
                ('kecamatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pemilu2024.kecamatan', verbose_name='Kecamatan')),
            ],
            options={
                'verbose_name': 'Kelurahan/Desa',
                'verbose_name_plural': 'Data Kelurahan/Desa',
                'ordering': ['kabupaten', 'kecamatan', 'desa_kelurahan'],
                'unique_together': {('kabupaten', 'kecamatan', 'desa_kelurahan')},
            },
        ),
    ]
