# Generated by Django 4.2 on 2026-02-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemilu2024', '0007_kelurahandesa'),
    ]

    operations = [
        migrations.CreateModel(
            name='DapilRI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True, verbose_name='Nama Dapil RI')),
                ('alokasi_kursi', models.PositiveIntegerField(verbose_name='Alokasi Kursi')),
                ('wilayah', models.ManyToManyField(help_text='Pilih satu atau lebih Kabupaten/Kota yang masuk ke Dapil ini', related_name='dapil_ri_set', to='pemilu2024.kabupatenkota', verbose_name='Wilayah Cakupan (Kab/Kota)')),
            ],
            options={
                'verbose_name': 'Dapil RI',
                'verbose_name_plural': 'Data Dapil RI',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='DapilProvinsi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True, verbose_name='Nama Dapil Provinsi')),
                ('alokasi_kursi', models.PositiveIntegerField(verbose_name='Alokasi Kursi')),
                ('wilayah', models.ManyToManyField(help_text='Pilih satu atau lebih Kabupaten/Kota yang masuk ke Dapil ini', related_name='dapil_prov_set', to='pemilu2024.kabupatenkota', verbose_name='Wilayah Cakupan (Kab/Kota)')),
            ],
            options={
                'verbose_name': 'Dapil Provinsi',
                'verbose_name_plural': 'Data Dapil Provinsi',
                'ordering': ['nama'],
            },
        ),
    ]
