# Generated by Django 4.2 on 2026-02-16 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pemilu2024', '0008_dapilri_dapilprovinsi'),
    ]

    operations = [
        migrations.CreateModel(
            name='DapilKabKota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Dapil Kab/Kota')),
                ('alokasi_kursi', models.PositiveIntegerField(verbose_name='Alokasi Kursi')),
                ('kabupaten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pemilu2024.kabupatenkota', verbose_name='Kabupaten/Kota')),
                ('wilayah_desa', models.ManyToManyField(blank=True, help_text='Pilih Desa/Kelurahan tertentu (untuk Kecamatan yang terbagi ke Dapil berbeda)', to='pemilu2024.kelurahandesa', verbose_name='Desa/Kelurahan Eceran')),
                ('wilayah_kecamatan', models.ManyToManyField(blank=True, help_text='Pilih Kecamatan yang masuk secara keseluruhan ke Dapil ini', to='pemilu2024.kecamatan', verbose_name='Kecamatan Utuh')),
            ],
            options={
                'verbose_name': 'Dapil Kab/Kota',
                'verbose_name_plural': 'Data Dapil Kab/Kota',
                'ordering': ['kabupaten', 'nama'],
                'unique_together': {('kabupaten', 'nama')},
            },
        ),
    ]
