# Generated by Django 4.2 on 2026-02-16 23:37

from django.db import migrations, models
import django.db.models.deletion
import pemilu2024.models


class Migration(migrations.Migration):

    dependencies = [
        ('pemilu2024', '0011_calegprovinsi'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalegKabKota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_urut', models.PositiveIntegerField(verbose_name='Nomor Urut')),
                ('nama', models.CharField(max_length=150, verbose_name='Nama Lengkap')),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1, verbose_name='Jenis Kelamin')),
                ('foto', models.ImageField(blank=True, null=True, upload_to=pemilu2024.models.caleg_kabkota_photo_path, verbose_name='Foto Caleg')),
                ('dapil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pemilu2024.dapilkabkota', verbose_name='Dapil Kab/Kota')),
                ('partai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pemilu2024.partai', verbose_name='Partai')),
            ],
            options={
                'verbose_name': 'Caleg DPRD Kab/Kota',
                'verbose_name_plural': 'Data Caleg DPRD Kab/Kota',
                'ordering': ['dapil', 'partai', 'nomor_urut'],
                'unique_together': {('dapil', 'partai', 'nomor_urut')},
            },
        ),
    ]
