# Generated by Django 4.2 on 2026-02-17 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pemilu2024', '0012_calegkabkota'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuaraTidakSahPilpres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_tidak_sah', models.PositiveIntegerField(default=0, verbose_name='Jumlah Suara Tidak Sah')),
                ('desa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suara_tidak_sah_pilpres', to='pemilu2024.kelurahandesa', verbose_name='Desa/Kelurahan')),
            ],
            options={
                'verbose_name': 'Suara Tidak Sah Pilpres',
                'verbose_name_plural': 'Data Suara Tidak Sah Pilpres',
            },
        ),
        migrations.CreateModel(
            name='PerolehanSuaraPilpres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_suara', models.PositiveIntegerField(default=0, verbose_name='Jumlah Suara Sah')),
                ('desa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perolehan_suara_pilpres', to='pemilu2024.kelurahandesa', verbose_name='Desa/Kelurahan')),
                ('paslon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pemilu2024.paslonpilpres', verbose_name='Pasangan Calon')),
            ],
            options={
                'verbose_name': 'Perolehan Suara Pilpres',
                'verbose_name_plural': 'Data Perolehan Suara Pilpres',
                'ordering': ['paslon__no_urut'],
                'unique_together': {('desa', 'paslon')},
            },
        ),
    ]
