# Generated by Django 4.2 on 2026-02-17 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pemilu2024', '0013_suaratidaksahpilpres_perolehansuarapilpres'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuaraPilpres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_suara', models.CharField(choices=[('sah', 'Suara Sah (Paslon)'), ('tidak_sah', 'Suara Tidak Sah')], default='sah', max_length=20, verbose_name='Jenis Suara')),
                ('jumlah_suara', models.PositiveIntegerField(default=0, verbose_name='Jumlah Suara')),
                ('desa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suara_pilpres', to='pemilu2024.kelurahandesa', verbose_name='Desa/Kelurahan')),
                ('paslon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pemilu2024.paslonpilpres', verbose_name='Pasangan Calon')),
            ],
            options={
                'verbose_name': 'Perolehan Suara Pilpres',
                'verbose_name_plural': 'Data Perolehan Suara Pilpres',
                'unique_together': {('desa', 'paslon', 'jenis_suara')},
            },
        ),
        migrations.RemoveField(
            model_name='suaratidaksahpilpres',
            name='desa',
        ),
        migrations.DeleteModel(
            name='PerolehanSuaraPilpres',
        ),
        migrations.DeleteModel(
            name='SuaraTidakSahPilpres',
        ),
    ]
