# Generated by Django 4.2 on 2026-02-17 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pemilu2024', '0014_suarapilpres_remove_suaratidaksahpilpres_desa_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='suarapilpres',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='suarapilpres',
            name='suara_paslon_1',
            field=models.PositiveIntegerField(default=0, verbose_name='Suara Paslon 01'),
        ),
        migrations.AddField(
            model_name='suarapilpres',
            name='suara_paslon_2',
            field=models.PositiveIntegerField(default=0, verbose_name='Suara Paslon 02'),
        ),
        migrations.AddField(
            model_name='suarapilpres',
            name='suara_paslon_3',
            field=models.PositiveIntegerField(default=0, verbose_name='Suara Paslon 03'),
        ),
        migrations.AddField(
            model_name='suarapilpres',
            name='suara_tidak_sah',
            field=models.PositiveIntegerField(default=0, verbose_name='Jumlah Suara Tidak Sah'),
        ),
        migrations.AlterField(
            model_name='suarapilpres',
            name='desa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rekap_suara_pilpres', to='pemilu2024.kelurahandesa', verbose_name='Desa/Kelurahan'),
        ),
        migrations.RemoveField(
            model_name='suarapilpres',
            name='jenis_suara',
        ),
        migrations.RemoveField(
            model_name='suarapilpres',
            name='jumlah_suara',
        ),
        migrations.RemoveField(
            model_name='suarapilpres',
            name='paslon',
        ),
    ]
