# Generated by Django 4.2 on 2026-02-17 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pemilu2024', '0015_alter_suarapilpres_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RekapTPSDPT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tps_pemilu', models.PositiveIntegerField(default=0, verbose_name='Jumlah TPS Pemilu')),
                ('dpt_pemilu', models.PositiveIntegerField(default=0, verbose_name='Jumlah DPT Pemilu')),
                ('tps_pilkada', models.PositiveIntegerField(default=0, verbose_name='Jumlah TPS Pilkada')),
                ('dpt_pilkada', models.PositiveIntegerField(default=0, verbose_name='Jumlah DPT Pilkada')),
                ('desa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rekap_tps_dpt', to='pemilu2024.kelurahandesa', verbose_name='Desa/Kelurahan')),
            ],
            options={
                'verbose_name': 'Data TPS & DPT',
                'verbose_name_plural': 'Data TPS & DPT',
            },
        ),
    ]
