# Generated by Django 4.2 on 2026-02-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemilu2024', '0016_rekaptpsdpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rekaptpsdpt',
            name='dpt_pilkada',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Jumlah DPT Pilkada'),
        ),
        migrations.AlterField(
            model_name='rekaptpsdpt',
            name='tps_pilkada',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Jumlah TPS Pilkada'),
        ),
    ]
