# Generated by Django 4.2 on 2026-02-17 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pemilu2024', '0017_alter_rekaptpsdpt_dpt_pilkada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rekaptpsdpt',
            name='dpt_pilkada',
        ),
        migrations.RemoveField(
            model_name='rekaptpsdpt',
            name='tps_pilkada',
        ),
    ]
