# Generated by Django 4.2 on 2026-02-17 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pemilu2024', '0018_remove_rekaptpsdpt_dpt_pilkada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuaraPilpresKecamatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suara_paslon_1', models.PositiveIntegerField(default=0, verbose_name='Suara Paslon 01')),
                ('suara_paslon_2', models.PositiveIntegerField(default=0, verbose_name='Suara Paslon 02')),
                ('suara_paslon_3', models.PositiveIntegerField(default=0, verbose_name='Suara Paslon 03')),
                ('suara_tidak_sah', models.PositiveIntegerField(default=0, verbose_name='Jumlah Suara Tidak Sah')),
                ('kecamatan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rekap_suara_pilpres_kecamatan', to='pemilu2024.kecamatan', verbose_name='Kecamatan')),
            ],
            options={
                'verbose_name': 'Rekap Suara Pilpres Kecamatan',
                'verbose_name_plural': 'Rekap Suara Pilpres Kecamatan',
            },
        ),
        migrations.CreateModel(
            name='RekapTPSDPTKecamatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tps_pemilu', models.PositiveIntegerField(default=0, verbose_name='Jumlah TPS Pemilu (Kecamatan)')),
                ('dpt_pemilu', models.PositiveIntegerField(default=0, verbose_name='Jumlah DPT Pemilu (Kecamatan)')),
                ('kecamatan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rekap_tps_dpt_kecamatan', to='pemilu2024.kecamatan', verbose_name='Kecamatan')),
            ],
            options={
                'verbose_name': 'Rekap TPS & DPT Kecamatan',
                'verbose_name_plural': 'Rekap TPS & DPT Kecamatan',
            },
        ),
    ]
