# Generated by Django 4.2 on 2026-02-18 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pemilu2024', '0019_suarapilpreskecamatan_rekaptpsdptkecamatan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calegkabkota',
            options={'ordering': ['dapil', 'partai', 'nomor_urut'], 'verbose_name': 'Caleg DPRD Kab/Kota', 'verbose_name_plural': 'Data Caleg Kokab'},
        ),
        migrations.AlterModelOptions(
            name='calegprovinsi',
            options={'ordering': ['dapil', 'partai', 'nomor_urut'], 'verbose_name': 'Caleg DPRD Provinsi', 'verbose_name_plural': 'Data Caleg Provinsi'},
        ),
        migrations.AlterModelOptions(
            name='calegri',
            options={'ordering': ['dapil', 'partai', 'nomor_urut'], 'verbose_name': 'Caleg DPR RI', 'verbose_name_plural': 'Data Caleg RI'},
        ),
        migrations.AlterModelOptions(
            name='dapilkabkota',
            options={'ordering': ['kabupaten', 'nama'], 'verbose_name': 'Dapil Kab/Kota', 'verbose_name_plural': 'Data Dapil Kokab'},
        ),
        migrations.AlterModelOptions(
            name='kabupatenkota',
            options={'ordering': ['nama'], 'verbose_name': 'Kabupaten/Kota', 'verbose_name_plural': 'Data Kokab'},
        ),
        migrations.AlterModelOptions(
            name='kelurahandesa',
            options={'ordering': ['kabupaten', 'kecamatan', 'desa_kelurahan'], 'verbose_name': 'Kelurahan/Desa', 'verbose_name_plural': 'Data DesKel'},
        ),
        migrations.CreateModel(
            name='GeoKokab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vektor_wilayah', models.TextField(blank=True, help_text='Paste kode GeoJSON batas wilayah di sini', null=True, verbose_name='Data Vektor (GeoJSON)')),
                ('warna_area', models.CharField(default='#CC0000', max_length=7, verbose_name='Warna Area (Hex)')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('kokab', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geodata', to='pemilu2024.kabupatenkota', verbose_name='Kabupaten/Kota')),
            ],
            options={
                'verbose_name': 'Geo Kokab',
                'verbose_name_plural': 'Peta Batas Kokab',
            },
        ),
        migrations.CreateModel(
            name='GeoKecamatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vektor_wilayah', models.TextField(blank=True, null=True, verbose_name='Data Vektor (GeoJSON)')),
                ('warna_area', models.CharField(default='#00CC00', max_length=7)),
                ('kecamatan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geodata', to='pemilu2024.kecamatan', verbose_name='Kecamatan')),
            ],
            options={
                'verbose_name': 'Geo Kecamatan',
                'verbose_name_plural': 'Peta Batas Kecamatan',
            },
        ),
        migrations.CreateModel(
            name='GeoDesKel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vektor_wilayah', models.TextField(blank=True, null=True, verbose_name='Data Vektor (GeoJSON)')),
                ('warna_area', models.CharField(default='#0000CC', max_length=7)),
                ('deskel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geodata', to='pemilu2024.kelurahandesa', verbose_name='Desa/Kelurahan')),
            ],
            options={
                'verbose_name': 'Geo DesKel',
                'verbose_name_plural': 'Peta Batas DesKel',
            },
        ),
    ]
