# Generated by Django 4.2 on 2026-02-18 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemilu2024', '0020_alter_calegkabkota_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partai',
            name='warna',
            field=models.CharField(default='#000000', help_text='Format: #RRGGBB', max_length=7, verbose_name='Warna Identitas (Hex)'),
        ),
        migrations.AddField(
            model_name='paslonpilpres',
            name='warna',
            field=models.CharField(default='#000000', help_text='Format: #RRGGBB', max_length=7, verbose_name='Warna Identitas (Hex)'),
        ),
        migrations.AlterField(
            model_name='geodeskel',
            name='warna_area',
            field=models.CharField(default='#808080', editable=False, max_length=7, verbose_name='Warna Area (Hex)'),
        ),
        migrations.AlterField(
            model_name='geokecamatan',
            name='warna_area',
            field=models.CharField(default='#808080', editable=False, max_length=7, verbose_name='Warna Area (Hex)'),
        ),
        migrations.AlterField(
            model_name='geokokab',
            name='warna_area',
            field=models.CharField(default='#808080', editable=False, max_length=7, verbose_name='Warna Area (Hex)'),
        ),
    ]
