# Generated by Django 4.2 on 2026-02-18 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemilu2024', '0021_partai_warna_paslonpilpres_warna_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geodeskel',
            name='warna_area',
            field=models.CharField(default='#808080', max_length=7, verbose_name='Warna Area (Hex)'),
        ),
        migrations.AlterField(
            model_name='geokecamatan',
            name='warna_area',
            field=models.CharField(default='#808080', max_length=7, verbose_name='Warna Area (Hex)'),
        ),
        migrations.AlterField(
            model_name='geokokab',
            name='warna_area',
            field=models.CharField(default='#808080', max_length=7, verbose_name='Warna Area (Hex)'),
        ),
    ]
