# Generated by Django 4.2 on 2026-02-19 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pemilu2024', '0022_alter_geodeskel_warna_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geokecamatan',
            name='kecamatan',
        ),
        migrations.RemoveField(
            model_name='geokokab',
            name='kokab',
        ),
        migrations.DeleteModel(
            name='GeoDesKel',
        ),
        migrations.DeleteModel(
            name='GeoKecamatan',
        ),
        migrations.DeleteModel(
            name='GeoKokab',
        ),
    ]
