# Generated by Django 4.2 on 2026-02-19 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pemilu2024', '0023_remove_geokecamatan_kecamatan_remove_geokokab_kokab_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoKokab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vektor_wilayah', models.TextField(blank=True, help_text='Paste kode GeoJSON batas wilayah di sini', null=True, verbose_name='Data Vektor (GeoJSON)')),
                ('warna_area', models.CharField(default='#808080', max_length=7, verbose_name='Warna Area (Hex)')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('kokab', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geodata', to='pemilu2024.kabupatenkota', verbose_name='Kabupaten/Kota')),
            ],
            options={
                'verbose_name': 'Geo Kokab',
                'verbose_name_plural': 'Peta Batas Kokab',
            },
        ),
        migrations.CreateModel(
            name='GeoKecamatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vektor_wilayah', models.TextField(blank=True, null=True, verbose_name='Data Vektor (GeoJSON)')),
                ('warna_area', models.CharField(default='#808080', max_length=7, verbose_name='Warna Area (Hex)')),
                ('kecamatan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geodata', to='pemilu2024.kecamatan', verbose_name='Kecamatan')),
            ],
            options={
                'verbose_name': 'Geo Kecamatan',
                'verbose_name_plural': 'Peta Batas Kecamatan',
            },
        ),
        migrations.CreateModel(
            name='GeoDesKel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vektor_wilayah', models.TextField(blank=True, null=True, verbose_name='Data Vektor (GeoJSON)')),
                ('warna_area', models.CharField(default='#808080', max_length=7, verbose_name='Warna Area (Hex)')),
                ('deskel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geodata', to='pemilu2024.kelurahandesa', verbose_name='Desa/Kelurahan')),
            ],
            options={
                'verbose_name': 'Geo DesKel',
                'verbose_name_plural': 'Peta Batas DesKel',
            },
        ),
    ]
