# Generated by Django 4.2 on 2026-02-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geodeskel',
            name='vektor_wilayah',
            field=models.TextField(blank=True, help_text='Paste kode GeoJSON batas wilayah di sini', null=True, verbose_name='Data Vektor (GeoJSON)'),
        ),
    ]
