# Generated by Django 4.2 on 2026-02-20 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KoalisiPilpres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partai', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='koalisi_pilpres_terdaftar', to='core.partai', verbose_name='Partai')),
            ],
            options={
                'verbose_name': 'Dukungan Partai (Koalisi)',
                'verbose_name_plural': 'Dukungan Partai (Koalisi)',
            },
        ),
        migrations.CreateModel(
            name='RekapSuaraPilpres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suara_tidak_sah', models.IntegerField(default=0, verbose_name='Suara Tidak Sah')),
                ('kecamatan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hasil_pilpres', to='core.kecamatan', verbose_name='Kecamatan')),
            ],
            options={
                'verbose_name': 'Rekap Suara Pilpres',
                'verbose_name_plural': 'Rekap Suara Pilpres',
                'db_table': 'pilpres_2024_rekapsuarapilpres',
            },
        ),
        migrations.CreateModel(
            name='PaslonPilpres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_urut', models.IntegerField(db_index=True, unique=True, verbose_name='No. Urut')),
                ('nama_capres', models.CharField(max_length=255, verbose_name='Nama Calon Presiden')),
                ('nama_cawapres', models.CharField(max_length=255, verbose_name='Nama Calon Wakil Presiden')),
                ('foto_paslon', models.ImageField(blank=True, null=True, upload_to='paslon_pilpres/', verbose_name='Foto Pasangan')),
                ('warna_hex', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Warna Identitas')),
                ('koalisi', models.ManyToManyField(related_name='paslon_pilpres_dijunjung', through='pilpres_2024.KoalisiPilpres', to='core.partai', verbose_name='Partai Koalisi')),
            ],
            options={
                'verbose_name': 'Paslon Pilpres 2024',
                'verbose_name_plural': 'Data Paslon Pilpres 2024',
                'ordering': ['no_urut'],
            },
        ),
        migrations.AddField(
            model_name='koalisipilpres',
            name='paslon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daftar_koalisi', to='pilpres_2024.paslonpilpres', verbose_name='Dukungan Ke Paslon'),
        ),
        migrations.CreateModel(
            name='DetailSuaraPaslon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_suara', models.IntegerField(default=0, verbose_name='Jumlah Suara')),
                ('paslon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_suara_kecamatan', to='pilpres_2024.paslonpilpres', verbose_name='Paslon')),
                ('rekap_suara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rincian_suara', to='pilpres_2024.rekapsuarapilpres')),
            ],
            options={
                'verbose_name': 'Detail Suara Paslon',
                'unique_together': {('rekap_suara', 'paslon')},
            },
        ),
    ]
