# Generated by Django 4.2 on 2026-02-20 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pilpres_2024', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rekapsuarapilpres',
            table=None,
        ),
    ]
