# Generated by Django 4.2 on 2026-02-21 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_tpsdptpemilu_options_and_more'),
        ('pilpres_2024', '0002_alter_rekapsuarapilpres_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='KabupatenPilpres',
            fields=[
            ],
            options={
                'verbose_name': 'Rekap Kabupaten Pilpres',
                'verbose_name_plural': 'Rekap Kabupaten Pilpres',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.kabupatenkota',),
        ),
        migrations.AlterModelOptions(
            name='detailsuarapaslon',
            options={'verbose_name': 'Detail Suara Paslon', 'verbose_name_plural': 'Detail Suara Paslon'},
        ),
        migrations.AlterField(
            model_name='detailsuarapaslon',
            name='jumlah_suara',
            field=models.IntegerField(default=0, verbose_name='Jumlah Suara Sah'),
        ),
        migrations.AlterField(
            model_name='detailsuarapaslon',
            name='rekap_suara',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rincian_suara', to='pilpres_2024.rekapsuarapilpres', verbose_name='Rekap Suara'),
        ),
    ]
