# Generated by Django 4.2 on 2026-02-21 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_tpsdptpemilu_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalegRI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_urut', models.IntegerField(verbose_name='No. Urut')),
                ('nama', models.CharField(max_length=255, verbose_name='Nama Lengkap')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='caleg_ri/', verbose_name='Foto Caleg')),
                ('daerah_pemilihan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caleg_ri_set', to='core.dapilri', verbose_name='Dapil RI')),
                ('partai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caleg_ri_set', to='core.partai', verbose_name='Partai')),
            ],
            options={
                'verbose_name': 'Caleg RI',
                'verbose_name_plural': 'Data Caleg RI',
                'ordering': ['daerah_pemilihan', 'partai__no_urut', 'no_urut'],
                'unique_together': {('no_urut', 'partai', 'daerah_pemilihan')},
            },
        ),
        migrations.CreateModel(
            name='RekapSuaraCalegRI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suara_tidak_sah', models.IntegerField(default=0, verbose_name='Suara Tidak Sah')),
                ('kecamatan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hasil_pileg_ri', to='core.kecamatan', verbose_name='Kecamatan')),
            ],
            options={
                'verbose_name': 'Rekap Suara Pileg RI',
                'verbose_name_plural': 'Rekap Suara Pileg RI',
            },
        ),
        migrations.CreateModel(
            name='DetailSuaraCalegRI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_suara', models.IntegerField(default=0, verbose_name='Jumlah Suara Sah')),
                ('caleg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_suara_kecamatan', to='pilegri_2024.calegri', verbose_name='Caleg')),
                ('rekap_suara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rincian_suara', to='pilegri_2024.rekapsuaracalegri', verbose_name='Rekap Suara')),
            ],
            options={
                'verbose_name': 'Detail Suara Caleg RI',
                'verbose_name_plural': 'Detail Suara Caleg RI',
                'unique_together': {('rekap_suara', 'caleg')},
            },
        ),
    ]
