# Generated by Django 4.2 on 2026-02-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_tpsdptpemilu_options_and_more'),
        ('pilegri_2024', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KabupatenPilegRI',
            fields=[
            ],
            options={
                'verbose_name': 'Rekap Kabupaten Pileg RI',
                'verbose_name_plural': 'Rekap Kabupaten Pileg RI',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.kabupatenkota',),
        ),
        migrations.AddField(
            model_name='calegri',
            name='jenis_kelamin',
            field=models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], default='L', max_length=1, verbose_name='Jenis Kelamin'),
        ),
    ]
