# Generated by Django 4.2 on 2026-02-21 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_tpsdptpemilu_options_and_more'),
        ('pilegri_2024', '0002_kabupatenpilegri_calegri_jenis_kelamin'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuaraPartaiRI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_suara', models.IntegerField(default=0, verbose_name='Suara Coblos Partai')),
                ('partai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suara_partai_ri_set', to='core.partai', verbose_name='Partai')),
                ('rekap_suara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rincian_suara_partai', to='pilegri_2024.rekapsuaracalegri', verbose_name='Rekap Suara')),
            ],
            options={
                'verbose_name': 'Suara Partai RI',
                'verbose_name_plural': 'Suara Partai RI',
                'unique_together': {('rekap_suara', 'partai')},
            },
        ),
    ]
