# Generated by Django 4.2 on 2026-02-21 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_tpsdptpemilu_options_and_more'),
        ('pilegri_2024', '0003_suarapartairi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CalegRI',
            new_name='RiCaleg',
        ),
        migrations.RenameModel(
            old_name='DetailSuaraCalegRI',
            new_name='RiDetail',
        ),
        migrations.RenameModel(
            old_name='SuaraPartaiRI',
            new_name='RiPartai',
        ),
        migrations.RenameModel(
            old_name='RekapSuaraCalegRI',
            new_name='RiRekap',
        ),
        migrations.CreateModel(
            name='KecamatanRIProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Kecamatan (Informasi RI)',
                'verbose_name_plural': 'Data Kecamatan (Informasi RI)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.kecamatan',),
        ),
        migrations.AlterModelOptions(
            name='ridetail',
            options={'verbose_name': 'Detail Suara RI', 'verbose_name_plural': 'Detail Suara RI'},
        ),
        migrations.AlterModelOptions(
            name='rirekap',
            options={'verbose_name': 'Rekap Suara RI', 'verbose_name_plural': 'Rekap Suara RI'},
        ),
        migrations.AlterModelTable(
            name='ricaleg',
            table='ri_caleg',
        ),
        migrations.AlterModelTable(
            name='ridetail',
            table='ri_detail',
        ),
        migrations.AlterModelTable(
            name='ripartai',
            table='ri_partai',
        ),
        migrations.AlterModelTable(
            name='rirekap',
            table='ri_rekap',
        ),
    ]
