# Generated by Django 4.2 on 2026-02-21 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_tpsdptpemilu_options_and_more'),
        ('pilegri_2024', '0004_rename_calegri_ricaleg_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RiCaleg',
            new_name='CalegRI',
        ),
        migrations.RenameModel(
            old_name='RiDetail',
            new_name='DetailSuaraRI',
        ),
        migrations.RenameModel(
            old_name='RiRekap',
            new_name='RekapSuaraRI',
        ),
        migrations.RenameModel(
            old_name='RiPartai',
            new_name='SuaraPartaiRI',
        ),
        migrations.AlterModelOptions(
            name='calegri',
            options={'ordering': ['daerah_pemilihan', 'partai__no_urut', 'no_urut'], 'verbose_name': 'Data Caleg RI', 'verbose_name_plural': 'Data Caleg RI'},
        ),
    ]
