# Generated by Django 4.2 on 2026-02-21 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pilegri_2024', '0005_rename_ricaleg_calegri_rename_ridetail_detailsuarari_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='calegri',
            table=None,
        ),
        migrations.AlterModelTable(
            name='detailsuarari',
            table=None,
        ),
        migrations.AlterModelTable(
            name='rekapsuarari',
            table=None,
        ),
        migrations.AlterModelTable(
            name='suarapartairi',
            table=None,
        ),
    ]
