# Generated by Django 4.2 on 2026-02-21 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_tpsdptpemilu_options_and_more'),
        ('pilegri_2024', '0006_alter_calegri_table_alter_detailsuarari_table_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CalegRI',
            new_name='Caleg',
        ),
        migrations.RenameModel(
            old_name='DetailSuaraRI',
            new_name='DetailSuaraCaleg',
        ),
        migrations.RenameModel(
            old_name='RekapSuaraRI',
            new_name='RekapSuara',
        ),
        migrations.RenameModel(
            old_name='SuaraPartaiRI',
            new_name='SuaraPartai',
        ),
    ]
