# Generated by Django 4.2 on 2026-02-28 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_tpsdptpemilu_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KecamatanGeoJSON',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geojson_data', models.JSONField(help_text="Format JSON / Koordinat batas peta. Gunakan format GeoJSON murni tanpa 'FeatureCollection'.", verbose_name='Data GeoJSON Polygon')),
                ('kecamatan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geojson_data', to='core.kecamatan', verbose_name='Kecamatan')),
            ],
            options={
                'verbose_name': 'Batas Peta Kecamatan',
                'verbose_name_plural': 'Batas Peta Kecamatan',
            },
        ),
        migrations.CreateModel(
            name='KabupatenGeoJSON',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geojson_data', models.JSONField(help_text="Format JSON / Koordinat batas peta. Gunakan format GeoJSON murni tanpa 'FeatureCollection'.", verbose_name='Data GeoJSON Polygon')),
                ('kabupaten', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geojson_data', to='core.kabupatenkota', verbose_name='Kabupaten/Kota')),
            ],
            options={
                'verbose_name': 'Batas Peta Kabupaten',
                'verbose_name_plural': 'Batas Peta Kabupaten',
            },
        ),
    ]
