# Generated by Django 4.2 on 2026-02-28 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geojson', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kabupatengeojson',
            options={'verbose_name': 'Batas Kokab', 'verbose_name_plural': 'Batas Kokab'},
        ),
        migrations.AlterModelOptions(
            name='kecamatangeojson',
            options={'verbose_name': 'Batas Peta Kecamatan', 'verbose_name_plural': 'Batas Kecamatan'},
        ),
        migrations.AlterField(
            model_name='kabupatengeojson',
            name='geojson_data',
            field=models.JSONField(blank=True, help_text="Format JSON / Koordinat batas peta. Gunakan format GeoJSON murni tanpa 'FeatureCollection'.", null=True, verbose_name='Data GeoJSON Polygon'),
        ),
        migrations.AlterField(
            model_name='kecamatangeojson',
            name='geojson_data',
            field=models.JSONField(blank=True, help_text="Format JSON / Koordinat batas peta. Gunakan format GeoJSON murni tanpa 'FeatureCollection'.", null=True, verbose_name='Data GeoJSON Polygon'),
        ),
    ]
